<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'id' => 1,
                'name_ar' => 'حلول البناء المعمارية | Architectural Building Solutions',
                'name_en' => 'Architectural Building Solutions',
                'slug' => 'architectural-building-solutions',
                'icon' => 'fa-building',
                'description' => 'حلول شاملة للبناء المعماري بما في ذلك فتحات السطح، حواجز الدرج، وأنظمة الحماية.',
                'image' => 'categories/nSYg8nTI1s65gK4JZrfN8Vq0vRsw1ZAkCjc6yGiY.jpg',
                'product_count' => 23,
                'sort_order' => 1,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 2,
                'name_ar' => 'أنظمة إدارة الكابلات | Cable Management Systems',
                'name_en' => 'Cable Management Systems',
                'slug' => 'cable-management-systems',
                'icon' => 'fa-network-wired',
                'description' => 'حلول متكاملة لإدارة وتنظيم الكابلات الكهربائية.',
                'image' => 'categories/SyARNqxAOqSZvyeT1FwmnidTZ58c0UIF1qNuoaVG.jpg',
                'product_count' => 6,
                'sort_order' => 3,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 3,
                'name_ar' => 'إكسسوارات البلوك والطينة ( اللياسة) | Blockwork & Plastering Accessories',
                'name_en' => 'Blockwork & Plastering Accessories',
                'slug' => 'blockwork-plastering-accessories',
                'icon' => 'fa-trowel-bricks',
                'description' => 'إكسسوارات متخصصة لأعمال البلوك والجص والتشطيبات.',
                'image' => 'categories/YPBrPxODAFQRe7qhJdwPmFByndTeDLX3xX3KdBQs.jpg',
                'product_count' => 11,
                'sort_order' => 4,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 4,
                'name_ar' => 'إكسسوارات قوالب الخرسانة | Concrete Formwork Accessories',
                'name_en' => 'Concrete Formwork Accessories',
                'slug' => 'concrete-formwork-accessories',
                'icon' => 'fa-cube',
                'description' => 'معدات وأدوات خاصة بأعمال قوالب الخرسانة.',
                'image' => 'categories/5JxNPJkb8kMX12BqIEoiARc5m6kEzAxziifkdrWq.jpg',
                'product_count' => 11,
                'sort_order' => 5,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 5,
                'name_ar' => 'العزل المائي والحراري | Waterproofing & Thermal Insulation',
                'name_en' => 'Waterproofing & Thermal Insulation',
                'slug' => 'waterproofing-thermal-insulation',
                'icon' => 'fa-shield-alt',
                'description' => 'مواد العزل المائي والحراري بأعلى معايير الجودة.',
                'image' => 'categories/IBu63lmZdr6I9m7LmmmHKLknQrPaQSjI8qbQ3JaB.jpg',
                'product_count' => 14,
                'sort_order' => 6,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 6,
                'name_ar' => 'مشابك الأنابيب والعلاقات | Pipe Clamps, Hangers & Fixings',
                'name_en' => 'Pipe Clamps, Hangers & Fixings',
                'slug' => 'pipe-clamps-hangers-fixings',
                'icon' => 'fa-link',
                'description' => 'أنظمة تثبيت متكاملة للأنابيب والكوابل.',
                'image' => 'categories/zffAity6jclpRbeBA4ONoRm2nbYgswJAICT4IKup.jpg',
                'product_count' => 9,
                'sort_order' => 7,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 7,
                'name_ar' => 'القواطع الجبسية والأسقف المعلقة | Gypsum Partitions & Suspended Ceilings',
                'name_en' => 'Gypsum Partitions & Suspended Ceilings',
                'slug' => 'gypsum-partitions-suspended-ceilings',
                'icon' => 'fa-border-all',
                'description' => 'حلول جبسية عصرية للمساحات الداخلية.',
                'image' => null,
                'product_count' => 15,
                'sort_order' => 8,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 8,
                'name_ar' => 'إكسسوارات الكلادينج والواجهات | Cladding & Facade Accessories',
                'name_en' => 'Cladding & Facade Accessories',
                'slug' => 'cladding-facade-accessories',
                'icon' => 'fa-layer-group',
                'description' => 'نظام متكامل لتكسية الواجهات بأعلى المعايير.',
                'image' => 'categories/7wnnhokCPp0WSg0AqVBGYsPYlIITVjwARRX5vWfh.jpg',
                'product_count' => 7,
                'sort_order' => 9,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 9,
                'name_ar' => 'المواد الاستهلاكية والأدوات | Consumable Items & Hardware',
                'name_en' => 'Consumable Items & Hardware',
                'slug' => 'consumable-items-hardware',
                'icon' => 'fa-screwdriver-wrench',
                'description' => 'تشكيلة واسعة من الأدوات المهنية والمواد الاستهلاكية.',
                'image' => 'categories/3l21K1OOTa0NNkkL5X4ayICw6utiF2YmwTrJPBlS.jpg',
                'product_count' => 6,
                'sort_order' => 11,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 10,
                'name_ar' => 'حلول هندسية لأعمال المعادن Metal Work Engineering Solution',
                'name_en' => 'Metal Work Engineering Solution',
                'slug' => 'metal-work-engineering-solution',
                'icon' => 'fa-folder',
                'description' => 'حلول هندسية متكاملة لأعمال المعادن تشمل التصميم والتصنيع والتركيب للهياكل المعدنية والدرابزين والأبواب والسياجات. نقدم لك منتجات عالية الجودة مصممة بدقة لتناسب مشاريعك السكنية والتجارية والصناعية مع ضمان المتانة والأمان.',
                'image' => 'categories/Hw0fYYhHg483eLsWRcQaTTZfhp4lhA8MDleUnXXW.jpg',
                'product_count' => 0,
                'sort_order' => 2,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 11,
                'name_ar' => 'مواد سباكة وصحية Plumbing and sanitary materials',
                'name_en' => 'Plumbing and sanitary materials',
                'slug' => 'plumbing-and-sanitary-materials',
                'icon' => 'fa-folder',
                'description' => 'مجموعة متكاملة من مواد السباكة والصحية عالية الجودة، تشمل الأنابيب، الوصلات، المحابس، المغاسل، والمراحيض. تتميز بمقاومة ممتازة للتسرب والصدأ والتآكل، بتصاميم عصرية تناسب جميع المشاريع السكنية والتجارية والصناعية.',
                'image' => 'categories/6jXxk3UCTkzZEnTjxHBVWeV6Zx8aXFU85M1VTv0O.jpg',
                'product_count' => 0,
                'sort_order' => 12,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
            [
                'id' => 12,
                'name_ar' => 'التجهيزات المرورية وسلامة الطرق (Traffic Safety & Control)',
                'name_en' => 'Traffic Safety & Control',
                'slug' => 'traffic-safety-control',
                'icon' => 'fa-folder',
                'description' => 'مجموعة متكاملة من تجهيزات السلامة المرورية والتحكم في حركة المرور، تشمل الحواجز، المطبات الصناعية، العواكس، اللوحات الإرشادية، والأعمدة الواقية. تتميز بجودة عالية، مقاومة للظروف الجوية والصدمات، لضمان أعلى مستويات الأمان على الطرق والمواقف والمنشآت.',
                'image' => null,
                'product_count' => 0,
                'sort_order' => 10,
                'is_active' => 1,
                'parent_id' => null,
                'description_en' => null,
                'meta_title' => null,
                'meta_description' => null,
                'is_featured' => 0,
            ],
        ];

        foreach ($categories as $category) {
            Category::updateOrCreate(
                ['id' => $category['id']],
                $category
            );
        }

        $this->command->info('Created sample categories from database.sql');
    }
}
