<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Warehouse;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Initial product catalog + opening stock, imported from Products.xlsx
 * (physical inventory count of the sanitary/plumbing hardware store).
 * No sale prices were supplied in the source sheet, so products are
 * seeded at price 0 and left active so stock/catalog data is usable
 * immediately; prices should be filled in via the admin panel.
 */
class SanitaryProductSeeder extends Seeder
{
    public function run(): void
    {
        $warehouse = Warehouse::firstOrCreate(
            ['code' => 'WH-001'],
            [
                'name' => 'Main Warehouse',
                'address' => null,
                'city' => null,
                'country' => null,
                'location_type' => 'warehouse',
                'capacity' => null,
                'is_active' => true,
                'is_primary' => true,
            ]
        );

        $products = [
            ['row' => 1, 'name_ar' => 'حفر tip on', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 2, 'name_ar' => 'طبش tip on', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 3, 'name_ar' => 'مفصلة ربط بابين', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 4, 'name_ar' => 'مفصلة 180 درجة هيدروليك', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 5, 'name_ar' => 'sr  fbz100b خلاط مغسلة شك قصير', 'sku' => 'L17', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 6, 'name_ar' => 'sr fbz100blخلاط مغسلة شك طويل', 'sku' => 'L16', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 7, 'name_ar' => 'اسافين سوبر 6م', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 8, 'name_ar' => 'اكسسوار حمام سايروس ثقيل', 'sku' => 'L116', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 9, 'name_ar' => 'اكسسوار حمام سايروس خفيف', 'sku' => 'L115', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 10, 'name_ar' => 'التيكو مع بخاخ', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 11, 'name_ar' => 'اوكرا سن كروم 2سم 1/2انش', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 16, 'in_stock' => true],
            ['row' => 12, 'name_ar' => 'اوكرا سن كروم 3سم 1/2انش', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 16, 'in_stock' => true],
            ['row' => 13, 'name_ar' => 'اوكرة بسن كروم 1/2 5 سم فوال', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 24, 'in_stock' => true],
            ['row' => 14, 'name_ar' => 'اوكرة حديد بسن 3/4', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 57, 'in_stock' => true],
            ['row' => 15, 'name_ar' => 'اوكرة سن كروم 4 سم', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 25, 'in_stock' => true],
            ['row' => 16, 'name_ar' => 'اوكره بسن كروم 3/4 / 1/2', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 17, 'name_ar' => 'اوكره حديد 3/4 انثى', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 18, 'name_ar' => 'بخاخ صدا', 'sku' => null, 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 19, 'name_ar' => 'براغي تثبيت كرسي', 'sku' => null, 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 20, 'name_ar' => 'بربيش تواليت كروم خفيف', 'sku' => 'L145', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 21, 'name_ar' => 'بربيش حمام 1م  سليكون رمادي خفيف', 'sku' => 'L146', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 22, 'name_ar' => 'بربيش حمام كروم 100مم', 'sku' => 'L149', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 23, 'name_ar' => 'بربيش دوش غروهي', 'sku' => 'L195', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 24, 'name_ar' => 'بربيش راصور حمام 150 سم', 'sku' => 'L148', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 25, 'name_ar' => 'بربيش سليكون حرير', 'sku' => 'L147', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 26, 'name_ar' => 'بربيش سليكون رمادي ثقيل 150سم', 'sku' => 'L131', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 27, 'name_ar' => 'بصاب عدم رجوع', 'sku' => 'L150', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 28, 'name_ar' => 'تلفون صغير', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 100, 'in_stock' => true],
            ['row' => 29, 'name_ar' => 'تي 1/2 انش كروم 304', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 30, 'name_ar' => 'تيب عزل اسود عريض', 'sku' => 'L206', 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 31, 'name_ar' => 'تيفلون سايروس 30 م', 'sku' => 'l199', 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 1007, 'in_stock' => true],
            ['row' => 32, 'name_ar' => 'جوان حشر', 'sku' => null, 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 50, 'in_stock' => true],
            ['row' => 33, 'name_ar' => 'جوان كرسي حمام كودو', 'sku' => 'L200', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 34, 'name_ar' => 'حمالة خزانين زاوية ثقيل', 'sku' => null, 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 35, 'name_ar' => 'حمالة خزانين زاوية خفيف', 'sku' => null, 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 36, 'name_ar' => 'حنفية PPR سن نحاس', 'sku' => 'L93', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 37, 'name_ar' => 'حنفية برم نحاس1/2 انش راكور', 'sku' => 'L151', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 38, 'name_ar' => 'حنفية برندا برم نحاس / 1/2 انش مصري', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 39, 'name_ar' => 'حنفية جداري مصري فوتيس راكور', 'sku' => 'L84', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 40, 'name_ar' => 'حنفية راكور فوتيس كروم', 'sku' => 'L101', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 41, 'name_ar' => 'حنفية دحل مازوت نحاس', 'sku' => 'L106', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 42, 'name_ar' => 'حنفية دحل نحاس 135غ صيني', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 43, 'name_ar' => 'حنفية دحل نحاس 200غ صيني', 'sku' => 'L152', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 44, 'name_ar' => 'حنفية دحل نحاس 210غ', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 45, 'name_ar' => 'حنفية راكور برم كروم مصري', 'sku' => 'L99', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 46, 'name_ar' => 'حنفية شك تركي', 'sku' => 'L9', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 47, 'name_ar' => 'حنفية شك مصري فوتيس', 'sku' => 'L211', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 48, 'name_ar' => 'حنفية غساله إيطالي 3/4ب1/2', 'sku' => 'L153', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 49, 'name_ar' => 'حنفية كروم طويلة', 'sku' => 'L64', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 50, 'name_ar' => 'حنفية كروم قصيرة', 'sku' => 'L97', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 51, 'name_ar' => 'حنفية كروم قصيرة نص برمة', 'sku' => 'L102', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 52, 'name_ar' => 'حنفية مصري طويلة كروم', 'sku' => 'L59', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 53, 'name_ar' => 'حنفية موديل بوغاتي نحاس', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 54, 'name_ar' => 'حنفية نحاس دحل تقيلة', 'sku' => 'L154', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 55, 'name_ar' => 'خلاط  حمام مصري كروم 200', 'sku' => 'L155', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 56, 'name_ar' => 'خلاط bsl جداري نحاس', 'sku' => 'L34', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 57, 'name_ar' => 'خلاط BSL حمام', 'sku' => 'L107', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 58, 'name_ar' => 'خلاط BSL شك نحاس', 'sku' => 'L36', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 59, 'name_ar' => 'خلاط ازرار مع سحابة موديل غروهي', 'sku' => 'L124', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 60, 'name_ar' => 'خلاط ايديال إيطالي', 'sku' => 'L1', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 61, 'name_ar' => 'خلاط تواليت sr fstz400b', 'sku' => 'L28', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 62, 'name_ar' => 'خلاط تواليت sr fstz410c', 'sku' => 'L27', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 63, 'name_ar' => 'خلاط تواليت كروم 304 جداري', 'sku' => 'L38', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 64, 'name_ar' => 'خلاط تواليت مع كباسة مصري كروم', 'sku' => 'L29', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 65, 'name_ar' => 'خلاط جداري غروهي', 'sku' => 'L121', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 66, 'name_ar' => 'خلاط جداري كوستا نحاس  BITEL', 'sku' => 'L104', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 67, 'name_ar' => 'خلاط حمام ذهبي مصري', 'sku' => 'L7', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 68, 'name_ar' => 'خلاط حمام غروهي', 'sku' => 'L122', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 69, 'name_ar' => 'خلاط حمام كروم مت مع سحابة 304', 'sku' => 'L42', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 70, 'name_ar' => 'خلاط حمام كوستا نحاس BITEL', 'sku' => 'L105', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 71, 'name_ar' => 'خلاط حمام مع دوش sr fsz 310c', 'sku' => 'L24', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 72, 'name_ar' => 'خلاط حمام مع دوش sr fsz300b', 'sku' => 'L26', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 73, 'name_ar' => 'خلاط حمام مع دوش sr fsz300c', 'sku' => 'L23', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 74, 'name_ar' => 'خلاط حمام مع دوش SR SFZ(تعديل)', 'sku' => 'L25', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 75, 'name_ar' => 'خلاط دفن جداري 2401', 'sku' => 'L79', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 76, 'name_ar' => 'خلاط زمك خفيف جداري', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 77, 'name_ar' => 'خلاط زمك خفيف حمام', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 78, 'name_ar' => 'خلاط زمك شك انفنتي', 'sku' => null, 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 79, 'name_ar' => 'خلاط شك طويل sr fbz100cl', 'sku' => 'L13', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 80, 'name_ar' => 'خلاط شك قصير fbz130c', 'sku' => 'L19', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 81, 'name_ar' => 'خلاط شك قصير sr fbb100c', 'sku' => 'L22', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 82, 'name_ar' => 'خلاط شك قصير sr fbz110c', 'sku' => 'L20', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 83, 'name_ar' => 'خلاط شك قصير sr fbz140c', 'sku' => 'L21', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 84, 'name_ar' => 'خلاط شك قصير غروهي', 'sku' => 'L138', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 85, 'name_ar' => 'خلاط شك كوستا نحاس BITEL', 'sku' => 'L197', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 86, 'name_ar' => 'خلاط شك مجلى مصري ذهبي', 'sku' => 'L8', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 87, 'name_ar' => 'خلاط شك مصري كروم مجلى 200', 'sku' => 'L117', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 88, 'name_ar' => 'خلاط شك مغسلة طويل sr fbz120cl', 'sku' => 'L15', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 89, 'name_ar' => 'خلاط شك مغسلة قصير sr fbz120c', 'sku' => 'L18', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 90, 'name_ar' => 'خلاط شيف معكوف', 'sku' => 'L80', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 91, 'name_ar' => 'خلاط عالي غروهي', 'sku' => 'L136', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 92, 'name_ar' => 'خلاط كروم مت 304 شك مجلى', 'sku' => 'L33', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 93, 'name_ar' => 'خلاط كروم مت 304 شك معكوف', 'sku' => 'L31', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 94, 'name_ar' => 'خلاط مجلى  غروهي', 'sku' => 'L137', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 95, 'name_ar' => 'خلاط مجلى راصور', 'sku' => 'L10', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 96, 'name_ar' => 'خلاط مجلىsr fkz200b', 'sku' => 'L14', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 97, 'name_ar' => 'خلاط مجلىsr fkz200c', 'sku' => 'L12', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 98, 'name_ar' => 'خلاط مصري اسود حمام', 'sku' => 'L81', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 99, 'name_ar' => 'خلاط مصري اسود مجلى شك', 'sku' => 'L126', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 100, 'name_ar' => 'خلاط مصري اسود مغسلة جداري', 'sku' => 'L78', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 101, 'name_ar' => 'خلاط مصري كروم معكوف 200', 'sku' => 'L71', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 102, 'name_ar' => 'خلاط معكوف مغسلة ذهبي مصري', 'sku' => 'L74', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 103, 'name_ar' => 'خلاط مغسلة شك كروم 304', 'sku' => 'L32', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 104, 'name_ar' => 'خلاط مغسلة مصري كروم 200', 'sku' => 'L72', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 105, 'name_ar' => 'دسك قص + حف 7', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 106, 'name_ar' => 'دسك قص وحف 4,5مم', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 107, 'name_ar' => 'دولاب عشراوية عادي', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 108, 'name_ar' => 'رقبة خلاط خفيف عكازة', 'sku' => 'L156', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 109, 'name_ar' => 'رقبة خلاط خفيف مد', 'sku' => 'L157', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 110, 'name_ar' => 'رقبة خلاط كروم تقيل قصيرة', 'sku' => 'L158', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 111, 'name_ar' => 'رقبة خلاط كروم كوبرا', 'sku' => 'L159', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 112, 'name_ar' => 'رقبة سليكون مع طربوش هرم', 'sku' => 'L160', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 113, 'name_ar' => 'رقبة سليكون ملونة متحركة طربوش', 'sku' => 'L65', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 114, 'name_ar' => 'رقبة كروم متحركة طربوش', 'sku' => 'L140', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 115, 'name_ar' => 'رقبة ملونة متحركة بدون طربوش', 'sku' => 'L67', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 116, 'name_ar' => 'ريشة نمساوي باطون +حجر 150سم', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 117, 'name_ar' => 'ريغار 15ب15 فيتيكس', 'sku' => 'L127', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 118, 'name_ar' => 'ريكار 30*30 ريزين', 'sku' => 'L190', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 119, 'name_ar' => 'ريكار 35*35 ريزين', 'sku' => 'L191', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 120, 'name_ar' => 'ريكار 40*40 ريزين', 'sku' => 'L192', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 121, 'name_ar' => 'ريكار 60*60 ريزين', 'sku' => 'L193', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 122, 'name_ar' => 'زند طاقة قلاب', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 123, 'name_ar' => 'سحابة دبل صيني DAMO', 'sku' => 'L194', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 124, 'name_ar' => 'سحابة دبل غروهي', 'sku' => 'L123', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 125, 'name_ar' => 'سحابة دوش سريوس طاسة مدورة ابيض', 'sku' => 'L114', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 126, 'name_ar' => 'سحابة دوش سريوس طاسة مربعه اسود', 'sku' => 'L30', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 127, 'name_ar' => 'سحابة دوش صيني bsl', 'sku' => 'L132', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 128, 'name_ar' => 'سحابة دوش صيني خفيف مفردة mhb', 'sku' => null, 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 0, 'in_stock' => false],
            ['row' => 129, 'name_ar' => 'سحابة دوش كروم سيخ مدور mhb', 'sku' => 'L37', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 130, 'name_ar' => 'سكة خرادق 30  الى 55', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 131, 'name_ar' => 'سكر  نحاس 1/2 ثقيل', 'sku' => 'L91', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 132, 'name_ar' => 'سكر  نحاس 3/4 ثقيل', 'sku' => 'L89', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 133, 'name_ar' => 'سكر اعمى 1/2ب1/2 mhb', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 134, 'name_ar' => 'سكر اعمى 1/2ب3/4 MHB', 'sku' => 'L57', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 135, 'name_ar' => 'سكر اعمى 1/2ب3/8 MHB', 'sku' => 'L58', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 136, 'name_ar' => 'سكر اعمى خفيف الماجد', 'sku' => 'L103', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 137, 'name_ar' => 'سكر اعمى سيريوس 1/2ب1/2', 'sku' => 'L66', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 138, 'name_ar' => 'سكر اعمى سيريوس 1/2ب1/2 نص برمى', 'sku' => 'L60', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 139, 'name_ar' => 'سكر اعمى نحاس طبة صغيرة golden 1/2', 'sku' => 'L68', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 140, 'name_ar' => 'سكر دحل صيني 1/2 انش', 'sku' => 'L94', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 141, 'name_ar' => 'سكر دحل صيني 1انش 305غ', 'sku' => 'L87', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 142, 'name_ar' => 'سكر دحل صيني 3/4انش', 'sku' => 'L90', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 143, 'name_ar' => 'سكر سوبر مجوز', 'sku' => 'L61', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 144, 'name_ar' => 'سكر شمسة PPR قياس 25', 'sku' => 'L95', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 145, 'name_ar' => 'سكر غسالة نحاس صيني', 'sku' => 'L162', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 146, 'name_ar' => 'سكر غساله إيطالي', 'sku' => 'L153-2', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 147, 'name_ar' => 'سكر كروم شطاف مفرد تقيل', 'sku' => 'L83', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 148, 'name_ar' => 'سكر مجوز صيني فتحة جانبية', 'sku' => 'L98', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 149, 'name_ar' => 'سكر مجوز مع حمالة', 'sku' => 'L96', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 150, 'name_ar' => 'سكر نحاس دحل صني 1 انش', 'sku' => 'L119', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 12, 'in_stock' => true],
            ['row' => 151, 'name_ar' => 'سكر نحاس مصري تقيل 1 انش', 'sku' => 'L88', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 152, 'name_ar' => 'سكر نص دورة 5008 كروم', 'sku' => 'L62', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 153, 'name_ar' => 'سكر نص دورة 5015 اسود', 'sku' => 'L100', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 154, 'name_ar' => 'سكرسوبر مسطرة مجوز', 'sku' => 'L63', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 155, 'name_ar' => 'سليكون بلومات تركي 280غ', 'sku' => 'L163', 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 156, 'name_ar' => 'سليكون موديل هولندي (صيني)', 'sku' => 'L164', 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 157, 'name_ar' => 'سليكون هولندي 808', 'sku' => 'L165', 'category_slug' => 'general-plumbing-supplies', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 158, 'name_ar' => 'سماعة دوش خفيفة', 'sku' => null, 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 159, 'name_ar' => 'سماعة دوش راس متحرك', 'sku' => 'L44', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 160, 'name_ar' => 'سماعة دوش غروهي مع بربيش', 'sku' => 'L196', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 161, 'name_ar' => 'سماعة دوش كروم 304 مت', 'sku' => 'L43', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 162, 'name_ar' => 'سن ب عزقة 3/4 ب 1/2 كروم', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 163, 'name_ar' => 'سن بعزقة 3/4ب1/2', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 164, 'name_ar' => 'سن بعزقة كروم 1/2 انش', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 11, 'in_stock' => true],
            ['row' => 165, 'name_ar' => 'سن بعزقة كروم 3/4ب 1/2', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 11, 'in_stock' => true],
            ['row' => 166, 'name_ar' => 'سيخ دوش كروم 125سم', 'sku' => null, 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 167, 'name_ar' => 'سيخ سخان موديل ايطالي 90سم', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 168, 'name_ar' => 'شطاف  نحاس ذهبي اونكس', 'sku' => 'L134', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 169, 'name_ar' => 'شطاف فيدال كروم خفيف', 'sku' => null, 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 170, 'name_ar' => 'شطاف كروم ثقيل مت', 'sku' => 'L166', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 171, 'name_ar' => 'شطاف كروم سايروس', 'sku' => 'L52', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 172, 'name_ar' => 'شطاف كروم وسط كيس ازرق', 'sku' => 'L53', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 173, 'name_ar' => 'شطاف مع كباسة بيضاء خفيف', 'sku' => 'L56', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 174, 'name_ar' => 'شطاف نيمو كروم', 'sku' => 'L47', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 175, 'name_ar' => 'شمسة مسح', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 176, 'name_ar' => 'شمسة هرم', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 177, 'name_ar' => 'صباب مجلى نحاس قياس 9', 'sku' => 'L111', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 178, 'name_ar' => 'صباب مغسلة كروم mhb قياس 9', 'sku' => 'L110', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 179, 'name_ar' => 'صباب مغسلة كروم وسط قياس 9 زمك', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 180, 'name_ar' => 'طاسة دوش مدورة 33سم', 'sku' => 'L139', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 181, 'name_ar' => 'طاسة دوش مربعه 15س', 'sku' => 'L167', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 11, 'in_stock' => true],
            ['row' => 182, 'name_ar' => 'طبة ليزرية قرص 3سم المنيوم', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 183, 'name_ar' => 'طبة ليزرية قرص 5سم المنيوم', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 184, 'name_ar' => 'طقم شك اسود تركي خلاط mhb', 'sku' => 'L6', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 185, 'name_ar' => 'طقم شك ذهبي تركي  خلاط mhb', 'sku' => 'L73', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 186, 'name_ar' => 'طقم شك كروم تركي خلاط mhb', 'sku' => 'L75', 'category_slug' => 'faucets-and-valves', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 187, 'name_ar' => 'عدة كرسي اسباني فيتكس', 'sku' => 'L82', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 188, 'name_ar' => 'فواشة دبل صيني', 'sku' => 'L76', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 189, 'name_ar' => 'فواشة نحاس صيني 1/2 انش', 'sku' => 'L77', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 190, 'name_ar' => 'قلب سكر شمسة 1/2', 'sku' => 'L4', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 191, 'name_ar' => 'قلب سكر شمسة 3/4', 'sku' => 'L169', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 192, 'name_ar' => 'قلب نحاس 70غ صيني', 'sku' => 'L170', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 193, 'name_ar' => 'قلب نحاس إيطالي 70غ', 'sku' => 'L171', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 194, 'name_ar' => 'كباسة شطاف بلاستيك كروم', 'sku' => 'L55', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 195, 'name_ar' => 'كباسة شطاف بيضاء خفيف', 'sku' => 'L54', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 196, 'name_ar' => 'كباسة شطاف كروم ثفيل', 'sku' => 'L41', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 197, 'name_ar' => 'كباسة شطاف كروم لون اسود ثقيل', 'sku' => 'L40', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 198, 'name_ar' => 'كباسة غروهي', 'sku' => 'L70', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 199, 'name_ar' => 'كرت  دوش نيمو تقيل بكرتونة نيمو', 'sku' => 'L50', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 200, 'name_ar' => 'كرت دوش  اسود mhb كبيرة', 'sku' => 'L51', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 201, 'name_ar' => 'كرت دوش اسود بربيش دبل بولاد', 'sku' => 'L48', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 202, 'name_ar' => 'كرت دوش سماعة سودا', 'sku' => 'L46', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 203, 'name_ar' => 'كرت دوش سماعه خضرا', 'sku' => 'L49', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 204, 'name_ar' => 'كرت شطاف اسود', 'sku' => 'L39', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 205, 'name_ar' => 'كرت شطاف سكر مجوز', 'sku' => 'L85', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 7, 'in_stock' => true],
            ['row' => 206, 'name_ar' => 'كرت شطاف غروهي', 'sku' => 'L198', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 207, 'name_ar' => 'كوع انثى كروم 1/2 انش 304', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 208, 'name_ar' => 'كوع ذكر 1/2 انش كروم 304', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 209, 'name_ar' => 'مجلى 50*80سم', 'sku' => 'L172', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 210, 'name_ar' => 'مجلى بيانو', 'sku' => 'L135', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 211, 'name_ar' => 'مربط 1/2', 'sku' => 'L173', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 28, 'in_stock' => true],
            ['row' => 212, 'name_ar' => 'مسكة مدخل المنيوم باقي الألوان', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 213, 'name_ar' => 'مسكة منخل المنيوم لون خشبي', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 214, 'name_ar' => 'مصفاية 15ب15 فيتيكس ثقيلة', 'sku' => 'L128', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 215, 'name_ar' => 'مصفاية بلاطة f f زرقة 15 c', 'sku' => 'L174', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 4, 'in_stock' => true],
            ['row' => 216, 'name_ar' => 'مصفاية بلاطة ff خضرا 15 c', 'sku' => 'L175', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 217, 'name_ar' => 'مصفاية بلاطة شواية 8سم ب 30', 'sku' => 'L113', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 218, 'name_ar' => 'مصفاية بلاطة صيني 15 c علبة اسود', 'sku' => 'L176', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 219, 'name_ar' => 'مصفاية بلاطه سيفون 15 c', 'sku' => null, 'category_slug' => 'filters-and-drains', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 220, 'name_ar' => 'مفصلة 180 درجة بدون هيدروليك', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 221, 'name_ar' => 'مفصلة 45 درجة  بدون هيدروليك', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 222, 'name_ar' => 'مفصلة 45 درجة هيدروليك', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 223, 'name_ar' => 'مفصلة 60 غرام', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 224, 'name_ar' => 'مفصلة htc يدروليك', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 225, 'name_ar' => 'مفصلة شبح  120 htc', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 226, 'name_ar' => 'مفصلة طبش', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 227, 'name_ar' => 'مفصلة قزمة قصيرة', 'sku' => null, 'category_slug' => 'hinges', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 228, 'name_ar' => 'نقاصة حديد من 1و1/2 الى 1و1/4', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 229, 'name_ar' => 'نقاصة حديد من 1و1/2 الى 2', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 2, 'in_stock' => true],
            ['row' => 230, 'name_ar' => 'نقاصة حديد من 1و1/4 الى 3/4', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 231, 'name_ar' => 'نقاصة من 1و1/4 الى 2', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 232, 'name_ar' => 'هراب مجلى ابيض', 'sku' => 'L184', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 233, 'name_ar' => 'هراب مجلى اوسكار', 'sku' => 'L181', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 234, 'name_ar' => 'هراب مزدوج رمادي', 'sku' => 'L178', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 235, 'name_ar' => 'هراب مع صباب رمادي مغسلة', 'sku' => 'L179', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 236, 'name_ar' => 'هراب مع نقاصة سوبر', 'sku' => 'L180', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 20, 'in_stock' => true],
            ['row' => 237, 'name_ar' => 'هراب معغسلة wl رمادي قمع', 'sku' => 'L177', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 238, 'name_ar' => 'هراب مغسلة ابيض', 'sku' => 'L183', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 239, 'name_ar' => 'هراب مغسلة اوسكار', 'sku' => 'L182', 'category_slug' => 'sinks-and-basins', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 240, 'name_ar' => 'وجاء حمام 7دوزيم مبخوخ', 'sku' => 'L189', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 241, 'name_ar' => 'وجاء حمام ستانليس 7 دوزيم', 'sku' => 'L188', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 242, 'name_ar' => 'وصلة بولاد 3/8 ب 1/2 50سم', 'sku' => 'L144', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 243, 'name_ar' => 'وصلة بولاد 304 /50سم كروم', 'sku' => 'L143', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 11, 'in_stock' => true],
            ['row' => 244, 'name_ar' => 'وصلة بولاد 304 /60سم', 'sku' => 'L141', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 10, 'in_stock' => true],
            ['row' => 245, 'name_ar' => 'وصلة بولاد 304 /60سم ضغط عالي', 'sku' => 'L185', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 15, 'in_stock' => true],
            ['row' => 246, 'name_ar' => 'وصلة بولاد 304 /80سم', 'sku' => 'L142', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 12, 'in_stock' => true],
            ['row' => 247, 'name_ar' => 'وصلة بولاد 40 سم عادي', 'sku' => 'L186', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 248, 'name_ar' => 'وصلة بولاد 50 سم ضغط عالي عزقة نحاس', 'sku' => 'L187', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 249, 'name_ar' => 'كرسي معلق زنوبيا قصير', 'sku' => 'L202', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 250, 'name_ar' => 'كرسي معلق زنوبيا', 'sku' => 'L203', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 251, 'name_ar' => 'غطا كرسي هيدروليك', 'sku' => 'L204', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 252, 'name_ar' => 'غطا كرسي عادي', 'sku' => 'L205', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 253, 'name_ar' => 'سماعة دوش نيمو', 'sku' => 'L45', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 254, 'name_ar' => 'مصفاية 20c', 'sku' => 'L129', 'category_slug' => 'filters-and-drains', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 255, 'name_ar' => 'جوان فاصل بين خزان وكرسي', 'sku' => 'L201', 'category_slug' => 'toilet-seats-accessories', 'stock_quantity' => 5, 'in_stock' => true],
            ['row' => 256, 'name_ar' => 'sr ss700سحابة دوش   دبل طاسة مدورة ابيض', 'sku' => 'L114-2', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 3, 'in_stock' => true],
            ['row' => 257, 'name_ar' => 'sr ss750سحابة دوش طاسة مدورة اسود', 'sku' => 'L30-2', 'category_slug' => 'bathroom-accessories', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 258, 'name_ar' => 'سكر 2+1/2 ppr', 'sku' => 'L92', 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 259, 'name_ar' => 'مربط طبش 4 انش', 'sku' => 'L206-2', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 260, 'name_ar' => 'مربط طبش  3 انش', 'sku' => 'L207', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 18, 'in_stock' => true],
            ['row' => 261, 'name_ar' => 'مربط طبش 3/4 انش', 'sku' => 'L210', 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 45, 'in_stock' => true],
            ['row' => 262, 'name_ar' => 'وصلة شك بولاد 40 سم', 'sku' => null, 'category_slug' => 'pipes-and-fittings', 'stock_quantity' => 6, 'in_stock' => true],
            ['row' => 263, 'name_ar' => 'دسك قص + حف الماس', 'sku' => 'L131-2', 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 264, 'name_ar' => 'دسك قص + حف 4.50', 'sku' => 'L2', 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 1, 'in_stock' => true],
            ['row' => 265, 'name_ar' => 'ورق حف صيني', 'sku' => null, 'category_slug' => 'tools-and-hardware', 'stock_quantity' => 51, 'in_stock' => true],
            ['row' => 266, 'name_ar' => 'شمسة مسح كروم', 'sku' => null, 'category_slug' => 'elbows-and-valves', 'stock_quantity' => 200, 'in_stock' => true],
        ];

        $categoryIds = Category::whereIn('slug', collect($products)->pluck('category_slug')->unique())
            ->pluck('id', 'slug');

        foreach ($products as $data) {
            $categoryId = $categoryIds[$data['category_slug']] ?? null;
            $slugBase = $data['sku'] ? Str::slug($data['sku']) : null;
            $slug = $slugBase ? 'sp-' . $slugBase : 'sp-item-' . $data['row'];

            $identifier = $data['sku']
                ? ['sku' => $data['sku']]
                : ['slug' => $slug];

            $product = Product::updateOrCreate($identifier, [
                'name_ar' => $data['name_ar'],
                'slug' => $slug,
                'sku' => $data['sku'],
                'category_id' => $categoryId,
                'price' => 0,
                'stock_quantity' => $data['stock_quantity'],
                'unit' => 'قطعة',
                'min_stock' => 2,
                'in_stock' => $data['in_stock'],
                'is_active' => true,
                'is_featured' => false,
            ]);

            \App\Models\WarehouseInventory::updateOrCreate(
                [
                    'warehouse_id' => $warehouse->id,
                    'product_id' => $product->id,
                    'product_variant_id' => null,
                ],
                [
                    'quantity' => $data['stock_quantity'],
                    'reorder_point' => 5,
                    'safety_stock' => 2,
                ]
            );
        }

        $this->command->info('Seeded ' . count($products) . ' sanitary/plumbing products with opening stock');
    }
}
