import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        laravel({
            // `admin-mount.js` was a second entry point that hydrated Vue
            // components into blade pages under admin/{analytics,wms,workflows,
            // rma,notifications,audit}. No route ever rendered those pages — the
            // SPA catch-all owns `/admin/*` — and they loaded the entry through
            // a hardcoded `asset('build/assets/admin-mount.js')`, which stopped
            // resolving once the build started hashing filenames. So it was an
            // entry point, 42 eagerly imported components and 41 templates
            // serving pages nobody could reach.
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
        vue(),
    ],
    resolve: {
        alias: {
            '@': '/resources/js',
        },
    },
    build: {
        rollupOptions: {
            // Ignore PURE_ANNOTATION warnings generated by some dependencies
            onwarn(warning, warn) {
                if (warning && warning.code === 'PURE_ANNOTATION') return;
                warn(warning);
            },
            output: {
                // Content hashes are what make a rebuild visible to users.
                // These were overridden to bare `[name].js`, so every chunk kept
                // the same URL forever — browsers and proxies served the cached
                // copy and a deployed change only appeared after a hard refresh.
                // Laravel resolves these names through manifest.json, so nothing
                // needs to know the hashed filename.
                entryFileNames: 'assets/[name]-[hash].js',
                chunkFileNames: 'assets/[name]-[hash].js',
                assetFileNames: 'assets/[name]-[hash].[ext]',
                manualChunks: {
                    'vue-vendor': ['vue', 'vue-router', 'pinia'],
                    'element-plus': ['element-plus', '@element-plus/icons-vue'],
                    'axios': ['axios']
                }
            }
        },
        chunkSizeWarningLimit: 1500
    }
});
